export const data_one = {
	title: 'dummySection',
	data: [
		{
			listData: [
				{
					title: 'Luxury Spa Experience',
					coupons: 120,
					working: true,
					main_picture: 'path/to/spa1.jpg',
					highlights: 'Full day access, massage, complimentary drink',
					compensations: 'Free parking, towel service',
					fine_print: 'Valid weekdays only',
					description:
						'Rejuvenate with our full-day luxury spa package.',
					company: 1,
					location: 1,
					old_price: 120.0,
					new_price: 85.0,
					category: 1,
					subcategories: [1, 3],
					isVip: false,
					is_unique: false,
				},
				{
					title: 'Gourmet Dinner for Two',
					coupons: 150,
					working: true,
					main_picture: 'path/to/dinner2.jpg',
					highlights: '5-course meal, wine pairing',
					compensations: 'Valet parking',
					fine_print: 'Reservation required',
					description: 'An exclusive dining experience for two.',
					company: 2,
					location: 2,
					old_price: 250.0,
					new_price: 180.0,
					category: 2,
					subcategories: [2, 4],
					isVip: true,
					is_unique: true,
				},
				{
					title: 'City Sightseeing Tour',
					coupons: 75,
					working: false,
					main_picture: 'path/to/tour1.jpg',
					highlights: 'Guided tour, snacks included',
					compensations: '10% off next tour',
					fine_print: 'Fixed dates',
					description:
						"Explore the city's landmarks with a professional guide.",
					company: 3,
					location: 3,
					old_price: 100.0,
					new_price: 65.0,
					category: 3,
					subcategories: [3, 5],
					isVip: true,
					is_unique: false,
				},
				{
					title: 'Adventure Park Pass',
					coupons: 300,
					working: true,
					main_picture: 'path/to/adventure.jpg',
					highlights: 'Unlimited rides, snacks',
					compensations: 'Photo voucher',
					fine_print: 'Valid weekends only',
					description:
						'Full day access to all rides and attractions.',
					company: 4,
					location: 4,
					old_price: 80.0,
					new_price: 50.0,
					category: 4,
					subcategories: [6],
					isVip: false,
					is_unique: true,
				},
				{
					title: 'Fitness Club Membership',
					coupons: 200,
					working: true,
					main_picture: 'path/to/fitness.jpg',
					highlights: 'Access to all gym facilities',
					compensations: 'Free personal training session',
					fine_print: 'Monthly renewal',
					description: 'Join the best fitness club in the city.',
					company: 5,
					location: 5,
					old_price: 100.0,
					new_price: 70.0,
					category: 5,
					subcategories: [2, 3],
					isVip: false,
					is_unique: false,
				},
			],
		},
	],
};

export const data_Two = {
	title: 'not dummy',
	data: [
		{
			listData: [
				{
					title: 'Luxury Spa Experience',
					coupons: 120,
					working: true,
					main_picture: 'path/to/spa1.jpg',
					highlights: 'Full day access, massage, complimentary drink',
					compensations: 'Free parking, towel service',
					fine_print: 'Valid weekdays only',
					description:
						'Rejuvenate with our full-day luxury spa package.',
					company: 1,
					location: 1,
					old_price: 120.0,
					new_price: 85.0,
					category: 1,
					subcategories: [1, 3],
					isVip: false,
					is_unique: false,
				},
				{
					title: 'Gourmet Dinner for Two',
					coupons: 150,
					working: true,
					main_picture: 'path/to/dinner2.jpg',
					highlights: '5-course meal, wine pairing',
					compensations: 'Valet parking',
					fine_print: 'Reservation required',
					description: 'An exclusive dining experience for two.',
					company: 2,
					location: 2,
					old_price: 250.0,
					new_price: 180.0,
					category: 2,
					subcategories: [2, 4],
					isVip: true,
					is_unique: true,
				},
				{
					title: 'City Sightseeing Tour',
					coupons: 75,
					working: false,
					main_picture: 'path/to/tour1.jpg',
					highlights: 'Guided tour, snacks included',
					compensations: '10% off next tour',
					fine_print: 'Fixed dates',
					description:
						"Explore the city's landmarks with a professional guide.",
					company: 3,
					location: 3,
					old_price: 100.0,
					new_price: 65.0,
					category: 3,
					subcategories: [3, 5],
					isVip: true,
					is_unique: false,
				},
				{
					title: 'Adventure Park Pass',
					coupons: 300,
					working: true,
					main_picture: 'path/to/adventure.jpg',
					highlights: 'Unlimited rides, snacks',
					compensations: 'Photo voucher',
					fine_print: 'Valid weekends only',
					description:
						'Full day access to all rides and attractions.',
					company: 4,
					location: 4,
					old_price: 80.0,
					new_price: 50.0,
					category: 4,
					subcategories: [6],
					isVip: false,
					is_unique: true,
				},
				{
					title: 'Fitness Club Membership',
					coupons: 200,
					working: true,
					main_picture: 'path/to/fitness.jpg',
					highlights: 'Access to all gym facilities',
					compensations: 'Free personal training session',
					fine_print: 'Monthly renewal',
					description: 'Join the best fitness club in the city.',
					company: 5,
					location: 5,
					old_price: 100.0,
					new_price: 70.0,
					category: 5,
					subcategories: [2, 3],
					isVip: false,
					is_unique: false,
				},
			],
		},
	],
};

let data = [data_Two, data_one];
